spring:
  application:
    name: avic_ai
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/avic_ai
    username: root
    password: 123456
server:
  port: 12138
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.avir.ai.ctrl
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: 
      model-name: deepseek-chat
#      strict-json-schema: true
#      response-format: json_object
      log-requests: true
      log-responses: true
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: 
      model-name: deepseek-chat

      log-requests: true
      log-responses: true
bigmodel:
  api-key: 2f932e6d1d8e4887a873df2c2179b725.ZWtgFZJjG9AGIYXp

